### ISSUE TITLE
intégration page acceil

### ISSUE THREAD

**Issue by Abboudisara** [Abboudisara/C2N3_C3N3-#3]
- [x]  Intégration section Hero Header contenant Menu , Warning Info, Illustration et son texte et Boutton Test
- [x]  Intégration section Symptômes
- [x]  Intégration Recommandations officielles
- [x]  Intégration section Hero Footer contenant la section Test et le footer

**Comment by youssefbm** [comment]
Essayer d'optimiser le Code vers la fin, quand tu finira tous les pages.
